import React,{useEffect,useState} from 'react';
import {Image,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {MaterialIcons} from '@expo/vector-icons';
import MainDragCarousel from '../components/MainDragCarousel';
import {colors,fonts} from '../theme';
const LOGO_URL='https://raw.githubusercontent.com/momojdy/tiss_icons_assets/refs/heads/main/WantisslogoOuterless.PNG';
const slogans=['Buy Happiness','Wantiss','Sell Joy'];
const tabs=['Favs','For you','Flash','Locals','New Arrivals','Live','Categories...'];
const notifications=['new season styles, up to 20% off','free shipping on orders over $50','limited time: buy 1 get 1 half off'];
export default function MainHomePage(){
 const[slogan,setSlogan]=useState(1),[note,setNote]=useState(0);
 useEffect(()=>{const a=setInterval(()=>setSlogan(i=>(i+1)%3),3800),b=setInterval(()=>setNote(i=>(i+1)%3),3000);return()=>{clearInterval(a);clearInterval(b)}},[]);
 return <View style={styles.page}>
  <View style={styles.tabs}><MaterialIcons name="location-pin" size={26} color={colors.primary} style={styles.loc}/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.tabScroll}>{tabs.map((t,i)=><View key={t} style={[styles.tab,{width:t==='New Arrivals'?80:t==='For you'?65:t==='Categories...' ?100:70,backgroundColor:i===1?colors.white:'transparent'}]}><View style={styles.tabRow}><Text style={styles.tabText}>{t}</Text>{t==='Flash'&&<MaterialIcons name="bolt" size={17} color={colors.primary}/>}</View>{t==='Live'&&<View style={styles.live}><MaterialIcons name="play-arrow" size={13} color={colors.white}/></View>}</View>)}</ScrollView></View>
  <View style={styles.search}><MaterialIcons name="document-scanner" size={30} color={colors.primary}/><View style={styles.divider}/><View style={styles.slogan}><Text style={styles.sloganText}>{slogans[slogan]}</Text></View><MaterialIcons name="photo-camera" size={25} color="#888"/><Pressable style={styles.searchBtn}><Text style={styles.searchBtnText}>search</Text></Pressable></View>
  <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
   <MainDragCarousel/>
   <View style={styles.promo}><View style={styles.promoCards}><View style={styles.voucher}><Text style={styles.voucherText}>$7 grocery voucher</Text></View>{['$51.9 off','$10.5 off','$43.9 off'].map((x,i)=><View key={x} style={styles.promoCard}><View style={styles.promoFill}/><Text style={styles.promoCaption}>{x}</Text></View>)}</View><View style={styles.note}><MaterialIcons name="volume-up" size={16} color={colors.white}/><Text style={styles.noteText}>{notifications[note]}</Text></View></View>
   <View style={styles.grid}>{Array.from({length:6}).map((_,i)=><View key={i} style={styles.tile}/>)}</View>
  </ScrollView>
  <View style={styles.bottom}><View style={styles.nav}><View style={styles.logoCircle}><Image source={{uri:LOGO_URL}} style={styles.logo}/></View>{[['live-tv','Showcase'],['message','Messages'],['shopping-cart','Cart'],['tag-faces','Me']].map(([icon,label])=><View key={label} style={styles.navItem}><MaterialIcons name={icon as any} size={31} color={colors.primary}/><Text style={styles.navLabel}>{label}</Text></View>)}</View></View>
 </View>
}
const styles=StyleSheet.create({
page:{flex:1,backgroundColor:'#fff'},tabs:{height:100,backgroundColor:colors.barBackground,flexDirection:'row',alignItems:'flex-end'},loc:{marginLeft:12,marginBottom:15,marginRight:8},tabScroll:{alignItems:'flex-end'},tab:{height:50,marginRight:8,borderTopLeftRadius:30,borderTopRightRadius:50,alignItems:'center',justifyContent:'center',paddingHorizontal:7},tabRow:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:2},tabText:{fontFamily:fonts.semibold,fontSize:12,color:'#14181B',textAlign:'center'},live:{position:'absolute',right:5,bottom:4,width:20,height:20,borderRadius:10,backgroundColor:colors.gold,alignItems:'center',justifyContent:'center'},search:{marginTop:8,marginHorizontal:10,height:47,borderWidth:1.75,borderColor:colors.gold,borderRadius:10,flexDirection:'row',alignItems:'center',paddingLeft:2,paddingRight:4},divider:{width:1.8,height:30,backgroundColor:'#ccc',marginHorizontal:7},slogan:{width:211.6,height:47,alignItems:'center',justifyContent:'center'},sloganText:{fontFamily:fonts.slogan,fontSize:15,fontWeight:'400',color:'#14181B'},searchBtn:{height:30,paddingHorizontal:16,backgroundColor:colors.primary,borderRadius:8,alignItems:'center',justifyContent:'center',marginLeft:7},searchBtnText:{fontFamily:fonts.semibold,fontSize:13,color:'#fff'},content:{paddingTop:6,paddingBottom:105},promo:{marginTop:6,marginHorizontal:6,height:150,borderRadius:16,padding:10,backgroundColor:colors.promoPurple},promoCards:{height:98,flexDirection:'row',gap:6},voucher:{width:82,height:90,borderRadius:10,backgroundColor:'#fff',padding:7,justifyContent:'center'},voucherText:{fontFamily:fonts.semibold,fontSize:12,textAlign:'center'},promoCard:{flex:1,height:90,borderRadius:10,overflow:'hidden',position:'relative'},promoFill:{flex:1,backgroundColor:'#C9A8DE'},promoCaption:{position:'absolute',left:7,bottom:6,fontFamily:fonts.semibold,fontSize:11,color:'#fff'},note:{height:32,borderRadius:8,backgroundColor:'rgba(0,0,0,.55)',flexDirection:'row',alignItems:'center',paddingHorizontal:8,gap:7},noteText:{fontFamily:fonts.medium,fontSize:10,color:'#fff'},grid:{padding:8,flexDirection:'row',flexWrap:'wrap',gap:12},tile:{width:'47%',aspectRatio:1,borderRadius:12,backgroundColor:'#f4f4f4'},bottom:{position:'absolute',left:8,right:8,bottom:10,height:80,borderRadius:20,backgroundColor:'#fff',elevation:6,shadowOpacity:.12,shadowRadius:8,shadowOffset:{width:0,height:2},paddingHorizontal:2},nav:{flex:1,flexDirection:'row',alignItems:'center'},logoCircle:{width:60,height:60,borderRadius:30,borderWidth:1.5,borderColor:colors.navRing,alignItems:'center',justifyContent:'center',overflow:'hidden',marginHorizontal:3},logo:{width:58,height:58,borderRadius:29},navItem:{flex:1,height:76,alignItems:'center',justifyContent:'center'},navLabel:{fontFamily:fonts.semibold,fontSize:10,color:colors.primary,marginTop:1}
});
