import React, { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { MaterialCommunityIcons, MaterialIcons } from '@expo/vector-icons';
import { supabase } from '../lib/supabase';

const C={bg:'#F5F8F3',text:'#1A2517',muted:'#9AA595',green:'#3F6B37',tint:'#DCE8D2',strip:'#E6EDE1'};
const FILTERS=['All','Money','Points','Transfers'] as const;
type Filter=typeof FILTERS[number];
type Item={id:string;createdAt:string;title:string;subtitle:string;amount:number;currency:string;direction:'credit'|'debit';category:Exclude<Filter,'All'>;points:boolean};

const category=(r:any):Exclude<Filter,'All'>=>{const a=String(r.activity_category??'').toLowerCase(),t=String(r.transaction_type??'').toLowerCase();if(a==='points')return'Points';if(['send','receive','transfer','request','money_request'].includes(t))return'Transfers';return'Money';};
const dateText=(v:string)=>{const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleDateString(undefined,{month:'short',day:'numeric'})+' · '+d.toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'});};

function Header({onBack}:{onBack?:()=>void}){return<><View style={s.header}><Pressable onPress={onBack} style={s.headerButton} hitSlop={8}><MaterialIcons name="arrow-back" size={20} color={C.text}/></Pressable><Text style={s.headerTitle}>Recent Activity</Text></View><View style={s.strip}/></>;}
function Row({x}:{x:Item}){const amount=(x.direction==='debit'?'-':'+')+Math.abs(x.amount).toFixed(x.points?0:2)+' '+x.currency;return<View style={s.row}><View style={[s.icon,x.category==='Points'?s.dark:s.light]}><MaterialCommunityIcons name={x.category==='Points'?'stars':x.category==='Transfers'?'swap-horiz':'account-balance-wallet'} size={20} color={x.category==='Points'?C.tint:C.green}/></View><View style={s.copy}><Text style={s.title} numberOfLines={1}>{x.title}</Text><Text style={s.subtitle} numberOfLines={1}>{x.subtitle||dateText(x.createdAt)}</Text><Text style={s.date}>{dateText(x.createdAt)}</Text></View><Text style={[s.amount,x.direction==='debit'&&s.debit]}>{amount}</Text></View>;}
export default function WalletRecentActivityScreen({onBack}:{onBack?:()=>void}){const[filter,setFilter]=useState<Filter>('All');const[items,setItems]=useState<Item[]>([]);const[loading,setLoading]=useState(true);useEffect(()=>{let active=true;(async()=>{try{const{data,error}=await supabase.rpc('get_my_wallet_activity',{p_filter:'all',p_limit:500,p_offset:0});if(error)throw error;const cutoff=Date.now()-30*24*60*60*1000;const mapped=(Array.isArray(data)?data:[]).map((r:any):Item=>({id:String(r.id),createdAt:String(r.created_at),title:String(r.title??'Wallet transaction'),subtitle:String(r.subtitle??''),amount:Number(r.activity_category==='points'?(r.points_amount??0):(r.money_amount??0)),currency:String(r.activity_category==='points'?'pts':(r.money_currency??'USD')),direction:String(r.direction??'credit').toLowerCase()==='debit'?'debit':'credit',category:category(r),points:String(r.activity_category??'').toLowerCase()==='points'})).filter((x:Item)=>new Date(x.createdAt).getTime()>=cutoff);if(active)setItems(mapped.sort((a,b)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime()));}catch(e){console.error('Recent activity load error:',e);if(active)setItems([])}finally{if(active)setLoading(false)}})();return()=>{active=false}},[]);const filtered=useMemo(()=>filter==='All'?items:items.filter(x=>x.category===filter),[filter,items]);return<View style={s.page}><Header onBack={onBack}/><View style={s.filterWrap}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}>{FILTERS.map(x=><Pressable key={x} onPress={()=>setFilter(x)} style={[s.filter,x===filter&&s.selected]}><Text style={[s.filterText,x===filter&&s.selectedText]}>{x}</Text></Pressable>)}</ScrollView></View>{loading?<View style={s.center}><ActivityIndicator size="small" color={C.green}/></View>:filtered.length===0?<View style={s.empty}><View style={s.emptyIcon}><MaterialCommunityIcons name="history" size={34} color={C.muted}/></View><Text style={s.emptyTitle}>No recent activity</Text><Text style={s.emptyBody}>Your activity from the last 30 days will appear here.</Text></View>:<ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={s.list}>{filtered.map(x=><Row key={x.id} x={x}/>)}</ScrollView>}</View>;}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},header:{height:100,paddingHorizontal:10,paddingBottom:4,flexDirection:'row',alignItems:'flex-end',backgroundColor:C.bg},headerButton:{width:36,height:36,borderRadius:12,backgroundColor:C.tint,alignItems:'center',justifyContent:'center'},headerTitle:{marginLeft:12,paddingBottom:1,color:C.text,fontSize:19,lineHeight:23,fontFamily:'Inter_600SemiBold',transform:[{translateY:-4.5}]},strip:{height:20,backgroundColor:C.strip},filterWrap:{paddingTop:18},filters:{paddingHorizontal:16,gap:8},filter:{paddingHorizontal:14,paddingVertical:8,borderRadius:20,backgroundColor:C.tint},selected:{backgroundColor:C.text},filterText:{fontSize:12,lineHeight:14.5,fontFamily:'Inter_600SemiBold',color:C.green},selectedText:{color:'#FFFFFF'},list:{paddingHorizontal:16,paddingTop:12,paddingBottom:30},row:{minHeight:76,paddingVertical:12,flexDirection:'row',alignItems:'center',borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:'#E4EAE1'},icon:{width:42,height:42,alignItems:'center',justifyContent:'center'},light:{backgroundColor:C.tint,borderRadius:21},dark:{backgroundColor:C.green,borderRadius:12},copy:{flex:1,minWidth:0,marginLeft:12},title:{color:C.text,fontSize:13,fontFamily:'Inter_600SemiBold'},subtitle:{color:C.muted,fontSize:11.5,fontFamily:'Inter_400Regular',marginTop:4},date:{color:C.muted,fontSize:10.5,fontFamily:'Inter_400Regular',marginTop:3},amount:{marginLeft:10,color:C.green,fontSize:13,fontFamily:'Inter_600SemiBold'},debit:{color:C.text},center:{flex:1,alignItems:'center',justifyContent:'center'},empty:{flex:1,alignItems:'center',justifyContent:'center',paddingHorizontal:28,paddingBottom:100},emptyIcon:{width:92,height:92,borderRadius:46,backgroundColor:C.tint,alignItems:'center',justifyContent:'center',marginBottom:20},emptyTitle:{color:C.text,fontSize:20,fontFamily:'Inter_600SemiBold',marginBottom:8},emptyBody:{color:C.muted,fontSize:14,lineHeight:20,fontFamily:'Inter_400Regular',textAlign:'center',maxWidth:330}});
