import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import Svg, { Circle, Path, Rect } from 'react-native-svg';
import { Ionicons } from '@expo/vector-icons';

type Props={onPressViewAll?:()=>void;onPressToPay?:()=>void;onPressToShip?:()=>void;onPressToReceive?:()=>void;onPressToReview?:()=>void;onPressRefund?:()=>void};
const C='#25232A';
function Icon({type}:{type:'pay'|'ship'|'receive'|'review'|'refund'}){
 if(type==='pay')return <Svg width={22} height={22} viewBox="0 0 24 24"><Rect x="3.5" y="5" width="17" height="13" rx="2" fill="none" stroke={C} strokeWidth="1.35"/><Path d="M3.8 9.2h16.4M7 14h3" stroke={C} strokeWidth="1.35" strokeLinecap="round"/></Svg>;
 if(type==='ship')return <Svg width={22} height={22} viewBox="0 0 24 24"><Path d="M4 7.5 12 4l8 3.5v9L12 20l-8-3.5v-9Z" fill="none" stroke={C} strokeWidth="1.35" strokeLinejoin="round"/><Path d="M4.5 7.7 12 11l7.5-3.3M12 11v9" stroke={C} strokeWidth="1.35" strokeLinejoin="round"/></Svg>;
 if(type==='receive')return <Svg width={22} height={22} viewBox="0 0 24 24"><Path d="M3.5 7.5h11v10h-11zM14.5 11h3l3 3v3.5h-6" fill="none" stroke={C} strokeWidth="1.35" strokeLinejoin="round"/><Circle cx="7.5" cy="18" r="1.5" fill="none" stroke={C} strokeWidth="1.35"/><Circle cx="17.5" cy="18" r="1.5" fill="none" stroke={C} strokeWidth="1.35"/></Svg>;
 if(type==='review')return <Svg width={22} height={22} viewBox="0 0 24 24"><Path d="M5 5.5h14a2 2 0 0 1 2 2v7.5a2 2 0 0 1-2 2h-7l-4.5 3v-3H5a2 2 0 0 1-2-2v-7.5a2 2 0 0 1 2-2Z" fill="none" stroke={C} strokeWidth="1.35" strokeLinejoin="round"/><Path d="M7.5 10h9M7.5 13.5h5" stroke={C} strokeWidth="1.35" strokeLinecap="round"/></Svg>;
 return <Svg width={22} height={22} viewBox="0 0 24 24"><Path d="M19.5 9a7.5 7.5 0 1 0 1 5" fill="none" stroke={C} strokeWidth="1.35" strokeLinecap="round"/><Path d="M19.5 4.5v4h-4M12 9v5l3 1.5" fill="none" stroke={C} strokeWidth="1.35" strokeLinecap="round" strokeLinejoin="round"/></Svg>;
}
export default function MeOrdersCard({onPressViewAll,onPressToPay,onPressToShip,onPressToReceive,onPressToReview,onPressRefund}:Props){const items=[{type:'pay' as const,label:'To Pay',onPress:onPressToPay},{type:'ship' as const,label:'To Ship',onPress:onPressToShip},{type:'receive' as const,label:'To Receive',onPress:onPressToReceive},{type:'review' as const,label:'To Review',onPress:onPressToReview},{type:'refund' as const,label:'Refund / Support',onPress:onPressRefund}];return <View style={styles.card}><View style={styles.header}><Text style={styles.title}>My Orders</Text><Pressable style={styles.viewAll} onPress={onPressViewAll} hitSlop={6}><Text style={styles.viewAllText}>View All</Text><Ionicons name="chevron-forward" size={11} color="#8A8A8A"/></Pressable></View><View style={styles.itemsRow}>{items.map(i=><Pressable key={i.label} style={styles.item} onPress={i.onPress} hitSlop={5}><Icon type={i.type}/><Text style={styles.itemLabel} numberOfLines={1}>{i.label}</Text></Pressable>)}</View></View>}
const styles=StyleSheet.create({card:{marginHorizontal:12,marginTop:13,height:91,borderRadius:14,backgroundColor:'#FFFFFF',paddingHorizontal:6,paddingTop:10,shadowColor:'#E91E8C',shadowOpacity:.06,shadowRadius:6,shadowOffset:{width:0,height:2},elevation:1},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:8},title:{fontSize:15,lineHeight:18,fontWeight:'700',color:'#1C1C1C'},viewAll:{flexDirection:'row',alignItems:'center'},viewAllText:{fontSize:11,lineHeight:13,color:'#8A8A8A',marginRight:2},itemsRow:{flexDirection:'row',marginTop:10},item:{flex:1,alignItems:'center',justifyContent:'center'},itemLabel:{marginTop:6,fontSize:10,lineHeight:12,color:'#1C1C1C',fontWeight:'500',textAlign:'center'}});